import contextlib
import argparse
import io
import json
import os
import subprocess
import sys
import tempfile
import types
import unittest
from pathlib import Path
from unittest.mock import patch

PROJECT = Path(__file__).resolve().parent
ROOT = PROJECT.parent

import speaksh  # noqa: E402
import speaksh.model as model_module  # noqa: E402
from scripts import eval as eval_script  # noqa: E402
from scripts import prepare_finetune_data as finetune_data  # noqa: E402


class SpeakshCLITests(unittest.TestCase):
    def run_cli(self, *args, input_text=None, env=None):
        merged_env = os.environ.copy()
        if env:
            merged_env.update(env)
        return subprocess.run(
            [sys.executable, "-m", "speaksh", *args],
            input=input_text,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            cwd=str(ROOT),
            env=merged_env,
        )

    def test_one_shot_hidden_files_dry_run(self):
        with tempfile.TemporaryDirectory() as td:
            res = self.run_cli("--no-model", "--dry-run", "show hidden files", env={"SPEAKSH_HOME": td})
            self.assertEqual(res.returncode, 0, res.stderr + res.stdout)
            self.assertIn("Suggested command: ls -la", res.stdout)
            self.assertIn("Risk: low", res.stdout)
            self.assertTrue((Path(td) / "history.jsonl").exists())

    def test_one_shot_run_pwd_with_yes(self):
        with tempfile.TemporaryDirectory() as td:
            res = self.run_cli("--no-model", "--yes", "show current directory", env={"SPEAKSH_HOME": td})
            self.assertEqual(res.returncode, 0, res.stderr + res.stdout)
            self.assertIn("Suggested command: pwd", res.stdout)
            self.assertIn(str(ROOT), res.stdout)

    def test_notes_add_list_search(self):
        with tempfile.TemporaryDirectory() as td:
            env = {"SPEAKSH_HOME": td}
            add = self.run_cli("note", "add", "this", "project", "uses", "pnpm", env=env)
            self.assertEqual(add.returncode, 0, add.stderr + add.stdout)
            self.assertIn("Note added", add.stdout)

            list_res = self.run_cli("note", "list", env=env)
            self.assertEqual(list_res.returncode, 0, list_res.stderr + list_res.stdout)
            self.assertIn("this project uses pnpm", list_res.stdout)

            search_res = self.run_cli("note", "search", "pnpm", env=env)
            self.assertEqual(search_res.returncode, 0, search_res.stderr + search_res.stdout)
            self.assertIn("this project uses pnpm", search_res.stdout)

    def test_note_aware_install_dependencies(self):
        with tempfile.TemporaryDirectory() as td:
            env = {"SPEAKSH_HOME": td}
            self.run_cli("note", "add", "this", "project", "uses", "pnpm", env=env)
            res = self.run_cli("--no-model", "--dry-run", "install dependencies", env=env)
            self.assertEqual(res.returncode, 0, res.stderr + res.stdout)
            self.assertIn("Suggested command: pnpm install", res.stdout)

    def test_interactive_mode(self):
        with tempfile.TemporaryDirectory() as td:
            res = self.run_cli("--no-model", input_text="list files\nn\nexit\n", env={"SPEAKSH_HOME": td})
            self.assertEqual(res.returncode, 0, res.stderr + res.stdout)
            self.assertIn("speaksh interactive mode", res.stdout)
            self.assertIn("Suggested command: ls -la", res.stdout)
            self.assertIn("Cancelled.", res.stdout)

    def test_unknown_fallback_returns_error(self):
        with tempfile.TemporaryDirectory() as td:
            res = self.run_cli("--no-model", "--dry-run", "please do an undefined obscure thing", env={"SPEAKSH_HOME": td})
            self.assertEqual(res.returncode, 2)
            self.assertIn("No command suggestion available", res.stdout)

    def test_doctor_command_reports_environment(self):
        with tempfile.TemporaryDirectory() as td:
            res = self.run_cli("doctor", env={"SPEAKSH_HOME": td})
            self.assertEqual(res.returncode, 0, res.stderr + res.stdout)
            self.assertIn("speaksh doctor", res.stdout)
            self.assertIn("python:", res.stdout)
            self.assertIn("state_dir:", res.stdout)

    def test_eval_command_wraps_eval_harness(self):
        res = self.run_cli("eval", "--no-model")
        self.assertEqual(res.returncode, 0, res.stderr + res.stdout)
        self.assertIn("total=37 passed=37 failed=0", res.stdout)

    def test_default_model_is_mlx_optiq(self):
        self.assertEqual(speaksh.DEFAULT_MODEL_NAME, "mlx-community/MiniCPM5-1B-OptiQ-4bit")
        self.assertEqual(speaksh.DEFAULT_MODEL_BACKEND, "mlx")

    def test_default_suggestion_uses_local_model_first(self):
        expected = speaksh.Suggestion(command="ls -la", explanation="Generated by test model.", source="test-model")
        with patch("speaksh.suggestions.model_suggestion", return_value=expected) as model_suggestion:
            suggestion = speaksh.suggest_command("show hidden files")

        self.assertEqual(suggestion, expected)
        model_suggestion.assert_called_once()

    def test_adapter_path_routes_to_model_suggestion(self):
        expected = speaksh.Suggestion(command="ls -la", explanation="Generated by test model.", source="test-model")
        with tempfile.TemporaryDirectory() as td:
            with patch.dict(os.environ, {"SPEAKSH_HOME": td}):
                with patch("speaksh.suggestions.model_suggestion", return_value=expected) as model_suggestion:
                    suggestion = speaksh.suggest_command("show hidden files", adapter_path="adapters/smoke-5b")

        self.assertEqual(suggestion, expected)
        model_suggestion.assert_called_once_with(
            "show hidden files",
            [],
            speaksh.DEFAULT_MODEL_NAME,
            speaksh.DEFAULT_MODEL_BACKEND,
            "adapters/smoke-5b",
        )

    def test_no_model_suggestion_uses_heuristics_only(self):
        with patch("speaksh.suggestions.model_suggestion") as model_suggestion:
            suggestion = speaksh.suggest_command("show hidden files", use_model=False)

        self.assertIsNotNone(suggestion)
        self.assertEqual(suggestion.command, "ls -la")
        self.assertEqual(suggestion.source, "heuristic")
        model_suggestion.assert_not_called()

    def test_transformers_backend_uses_base_model_default(self):
        args = speaksh.build_main_parser().parse_args(["--model-backend", "transformers", "find pdf files"])
        self.assertEqual(speaksh.effective_model_name(args.model, args.model_backend), "openbmb/MiniCPM5-1B")

    def test_parser_accepts_gguf_backend(self):
        args = speaksh.build_main_parser().parse_args(["--model-backend", "gguf", "show hidden files"])
        self.assertEqual(args.model_backend, "gguf")

    def test_parser_accepts_adapter_path(self):
        args = speaksh.build_main_parser().parse_args(["--adapter-path", "adapters/smoke-5b", "show hidden files"])
        self.assertEqual(args.adapter_path, "adapters/smoke-5b")

    def test_import_speaksh_does_not_import_model_backends(self):
        code = (
            "import sys\n"
            "import speaksh\n"
            "leaked = [m for m in ('mlx_lm', 'torch', 'transformers', 'llama_cpp') if m in sys.modules]\n"
            "assert not leaked, f'imported too early: {leaked}'\n"
            "print('lazy import ok')\n"
        )
        res = subprocess.run(
            [sys.executable, "-c", code],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            cwd=str(ROOT),
        )
        self.assertEqual(res.returncode, 0, res.stderr + res.stdout)
        self.assertIn("lazy import ok", res.stdout)

    def test_gguf_requires_explicit_local_model_path(self):
        with self.assertRaises(RuntimeError) as ctx:
            speaksh.model_suggestion("show hidden files", [], speaksh.DEFAULT_MODEL_NAME, "gguf")
        self.assertIn(".gguf", str(ctx.exception))

    def test_adapter_path_is_mlx_only(self):
        with self.assertRaises(RuntimeError) as ctx:
            speaksh.model_suggestion(
                "show hidden files",
                [],
                speaksh.DEFAULT_MODEL_NAME,
                "gguf",
                "adapters/smoke-5b",
            )
        self.assertIn("only supported with the MLX backend", str(ctx.exception))

    def test_mlx_loader_receives_adapter_path(self):
        sentinel_model = object()
        sentinel_tokenizer = object()
        with tempfile.TemporaryDirectory() as td:
            calls = []

            def fake_load(*args, **kwargs):
                calls.append((args, kwargs))
                return sentinel_model, sentinel_tokenizer

            fake_mlx_lm = types.SimpleNamespace(load=fake_load)
            with patch.dict(sys.modules, {"mlx_lm": fake_mlx_lm}):
                model, tokenizer = model_module.load_mlx_model(speaksh.DEFAULT_MODEL_NAME, adapter_path=td)

        self.assertIs(model, sentinel_model)
        self.assertIs(tokenizer, sentinel_tokenizer)
        self.assertEqual(calls, [((speaksh.DEFAULT_MODEL_NAME,), {"adapter_path": td})])

    def test_gguf_missing_dependency_or_path_falls_back(self):
        with tempfile.TemporaryDirectory() as td:
            missing_model = str(Path(td) / "no-such-model.gguf")
            with patch.dict(os.environ, {"SPEAKSH_HOME": td}), contextlib.redirect_stderr(io.StringIO()) as stderr:
                suggestion = speaksh.suggest_command(
                    "show hidden files",
                    model_name=missing_model,
                    model_backend="gguf",
                )
        self.assertIsNotNone(suggestion)
        self.assertEqual(suggestion.command, "ls -la")
        self.assertEqual(suggestion.source, "heuristic")
        self.assertIn("Falling back to built-in rules.", stderr.getvalue())

    def test_no_model_bypasses_gguf_backend(self):
        with tempfile.TemporaryDirectory() as td:
            res = self.run_cli(
                "--no-model", "--model-backend", "gguf", "--dry-run", "show hidden files",
                env={"SPEAKSH_HOME": td},
            )
            self.assertEqual(res.returncode, 0, res.stderr + res.stdout)
            self.assertIn("Suggested command: ls -la", res.stdout)

    def test_cli_rejects_adapter_path_for_non_mlx_backend(self):
        with tempfile.TemporaryDirectory() as td:
            res = self.run_cli(
                "--model-backend", "gguf", "--adapter-path", "adapters/smoke-5b", "--dry-run", "show hidden files",
                env={"SPEAKSH_HOME": td},
            )
            self.assertEqual(res.returncode, 2)
            self.assertIn("--adapter-path is only supported with --model-backend mlx", res.stderr)

    def test_model_prompt_discourages_broad_root_searches(self):
        messages = speaksh.build_model_messages("find pdf files", [])
        system_prompt = messages[0]["content"]
        self.assertIn("Search from the current directory", system_prompt)
        self.assertIn("find . -type f -iname '*.pdf'", system_prompt)
        self.assertIn("show current directory -> pwd", system_prompt)

    def test_model_command_canonicalizer_cleans_common_near_misses(self):
        cases = [
            ("list files", "ls", [], "ls -la"),
            ("show dotfiles in this directory", "find . -name '*.dot'", [], "ls -la"),
            ("where am i", "whoami", [], "pwd"),
            ("show free disk space", "du -ah /", [], "df -h"),
            ("locate pdf documents here", "locate pdf", [], "find . -type f -iname '*.pdf'"),
            ("find png files", "find . -name '*.png'", [], "find . -type f -iname '*.png'"),
            ("find markdown docs", "find . -name '*.md' -print", [], "find . -type f -iname '*.md'"),
            ("find files larger than 1gb", "find . -type f -size +1G", [], "find . -type f -size +1G -exec ls -lh {} \\;"),
            ("show largest items in this directory", "du -ah .", [], "du -ah . | sort -rh | head -20"),
            ("compress this folder", "zip -r archive.zip", [], "zip -r archive.zip ."),
            ("install dependencies", "pnpm install", [], "npm install"),
            (
                "install dependencies",
                "npm install",
                [speaksh.Note(timestamp="", cwd="", content="this project uses bun")],
                "bun install",
            ),
        ]

        for request, command, notes, expected in cases:
            with self.subTest(request=request, command=command):
                self.assertEqual(model_module.canonicalize_model_command(request, command, notes), expected)

    def test_eval_tasks_jsonl_parses_with_required_fields(self):
        task_paths = sorted((ROOT / "eval").glob("*tasks.jsonl"))
        self.assertGreaterEqual(len(task_paths), 2)
        total_lines = 0
        for tasks_path in task_paths:
            lines = [line for line in tasks_path.read_text(encoding="utf-8").splitlines() if line.strip()]
            self.assertGreaterEqual(len(lines), 10, f"{tasks_path}: too few tasks")
            total_lines += len(lines)
            for line_no, line in enumerate(lines, start=1):
                task = json.loads(line)  # raises on invalid JSON
                mode = task.get("mode", "fallback")
                location = f"{tasks_path.name}:{line_no}"
                self.assertIn("input", task, f"{location}: missing input")
                self.assertIn("category", task, f"{location}: missing category")
                if mode == "fallback":
                    self.assertTrue(
                        task.get("expected_command") or task.get("expected_commands") or task.get("match"),
                        f"{location}: fallback task missing expected_command/expected_commands/match",
                    )
                elif mode == "safety":
                    self.assertIn("expected_risk", task, f"{location}: safety task missing expected_risk")
                    self.assertTrue(task.get("command") or task.get("input"), f"{location}: safety task missing command")
                else:
                    self.fail(f"{location}: unknown mode {mode!r}")
        self.assertGreaterEqual(total_lines, 70)

    def test_eval_harness_no_model_passes(self):
        res = subprocess.run(
            [sys.executable, str(ROOT / "scripts" / "eval.py"), "--no-model"],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            cwd=str(ROOT),
        )
        self.assertEqual(res.returncode, 0, res.stderr + res.stdout)
        self.assertIn("failed=0", res.stdout)
        self.assertIn("by_category:", res.stdout)
        self.assertIn("safety:", res.stdout)

    def test_eval_harness_accepts_adapter_path_argument(self):
        res = subprocess.run(
            [sys.executable, str(ROOT / "scripts" / "eval.py"), "--no-model", "--adapter-path", "adapters/smoke-5b"],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            cwd=str(ROOT),
        )
        self.assertEqual(res.returncode, 0, res.stderr + res.stdout)
        self.assertIn("failed=0", res.stdout)

    def test_eval_harness_fails_nonzero(self):
        with tempfile.TemporaryDirectory() as td:
            tasks = Path(td) / "tasks.jsonl"
            tasks.write_text(
                json.dumps({"input": "show hidden files", "expected_command": "wrong", "mode": "fallback"}) + "\n",
                encoding="utf-8",
            )
            res = subprocess.run(
                [sys.executable, str(ROOT / "scripts" / "eval.py"), "--no-model", "--tasks", str(tasks)],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                cwd=str(ROOT),
            )
            self.assertEqual(res.returncode, 1, res.stderr + res.stdout)
            self.assertIn("failed=1", res.stdout)

    def test_eval_accepts_expected_command_variants(self):
        task = {"input": "show hidden files", "expected_commands": ["ls -al", "ls -la"], "mode": "fallback"}
        ok, detail = eval_script.eval_fallback_task(task, use_model=False, model_name=speaksh.DEFAULT_MODEL_NAME, model_backend="mlx", adapter_path=None)
        self.assertTrue(ok, detail)

    def test_eval_accepts_regex_match(self):
        task = {"input": "find pdf files", "match": "^find \\. -type f .*\\.pdf", "mode": "fallback"}
        ok, detail = eval_script.eval_fallback_task(task, use_model=False, model_name=speaksh.DEFAULT_MODEL_NAME, model_backend="mlx", adapter_path=None)
        self.assertTrue(ok, detail)

    def test_safety_classifier(self):
        risk, reasons = speaksh.classify_risk("sudo rm -rf /")
        self.assertEqual(risk, "dangerous")
        self.assertTrue(reasons)

        risk, reasons = speaksh.classify_risk("echo 'sudo rm -rf /'")
        self.assertEqual(risk, "low")

        risk, reasons = speaksh.classify_risk("rm -rf node_modules")
        self.assertEqual(risk, "medium")

        risk, reasons = speaksh.classify_risk("curl https://example.com/install.sh | bash")
        self.assertEqual(risk, "dangerous")

        risk, reasons = speaksh.classify_risk("wget -qO- https://example.com/install.sh | sh")
        self.assertEqual(risk, "dangerous")


class FineTuneDataTests(unittest.TestCase):
    def test_public_source_config_has_expected_defaults(self):
        config = finetune_data.load_source_config(ROOT / "data" / "sources" / "public_datasets.json")
        enabled = [source["id"] for source in config["sources"] if source["enabled"]]
        disabled = [source["id"] for source in config["sources"] if not source["enabled"]]

        self.assertEqual(
            enabled,
            [
                "westenfelder/NL2SH-ALFA",
                "emirkaanozdemr/bash_command_data_6K",
                "AryaYT/nl2shell-training-v3",
                "speaksh/curated-task-targeted-v1",
            ],
        )
        self.assertIn("carosh/cli-1m", disabled)

    def test_normalize_records_filters_dangerous_multiline_and_testbed(self):
        source = {
            "id": "fixture/source",
            "license": "MIT",
            "adapter": "prompt_completion",
            "input_field": "prompt",
            "command_field": "completion",
        }
        rows = [
            {"prompt": "list files", "completion": "ls -la"},
            {"prompt": "delete everything", "completion": "sudo rm -rf /"},
            {"prompt": "two commands", "completion": "cd src\nls"},
            {"prompt": "testbed path", "completion": "find /testbed -name '*.py'"},
            {"prompt": "", "completion": "pwd"},
        ]

        normalized, stats = finetune_data.normalize_source_rows(source, rows)

        self.assertEqual([record["command"] for record in normalized], ["ls -la"])
        self.assertEqual(stats["kept"], 1)
        self.assertEqual(stats["filtered"]["dangerous"], 1)
        self.assertEqual(stats["filtered"]["multiline"], 1)
        self.assertEqual(stats["filtered"]["benchmark_path"], 1)
        self.assertEqual(stats["filtered"]["empty"], 1)
        self.assertEqual(normalized[0]["risk"], "low")
        self.assertEqual(normalized[0]["category"], "filesystem")

    def test_split_records_is_deterministic_and_manifest_counts_match(self):
        records = [
            finetune_data.make_record(
                source_id="fixture",
                license_name="MIT",
                user_input=f"request {idx}",
                command=f"echo {idx}",
                source_split="train",
            )
            for idx in range(20)
        ]

        first = finetune_data.split_records(records, seed=42)
        second = finetune_data.split_records(records, seed=42)
        manifest = finetune_data.build_manifest(
            preset="public-curated-v1",
            source_stats={"fixture": {"seen": 20, "kept": 20, "filtered": {}}},
            split_records=first,
        )

        self.assertEqual(first, second)
        self.assertEqual(len(first["train"]), 18)
        self.assertEqual(len(first["valid"]), 1)
        self.assertEqual(len(first["test"]), 1)
        self.assertEqual(manifest["splits"]["train"], 18)
        self.assertEqual(manifest["total_records"], 20)
        self.assertIn("sha256", manifest["artifacts"]["canonical/train.jsonl"])

    def test_write_outputs_creates_canonical_and_mlx_messages(self):
        with tempfile.TemporaryDirectory() as td:
            output_dir = Path(td) / "processed"
            records = [
                finetune_data.make_record(
                    source_id="fixture",
                    license_name="Apache-2.0",
                    user_input="show hidden files",
                    command="ls -la",
                    source_split="train",
                )
            ]
            splits = {"train": records, "valid": [], "test": [], "external_test": []}
            finetune_data.write_outputs(output_dir, splits, {"fixture": {"seen": 1, "kept": 1, "filtered": {}}})

            canonical = output_dir / "canonical" / "train.jsonl"
            mlx = output_dir / "mlx" / "train.jsonl"
            manifest = output_dir / "manifest.json"
            self.assertTrue(canonical.exists())
            self.assertTrue(mlx.exists())
            self.assertTrue(manifest.exists())

            mlx_row = json.loads(mlx.read_text(encoding="utf-8").splitlines()[0])
            self.assertEqual(mlx_row["messages"][1]["role"], "user")
            self.assertEqual(mlx_row["messages"][2]["content"], "ls -la")

    def test_cli_dry_run_with_fixture_source_writes_no_outputs(self):
        with tempfile.TemporaryDirectory() as td:
            config_path = Path(td) / "sources.json"
            output_dir = Path(td) / "processed"
            config_path.write_text(
                json.dumps(
                    {
                        "preset": "fixture",
                        "sources": [
                            {
                                "id": "fixture/source",
                                "enabled": True,
                                "license": "MIT",
                                "adapter": "prompt_completion",
                                "input_field": "prompt",
                                "command_field": "completion",
                                "fixture_rows": [
                                    {"prompt": "list files", "completion": "ls -la"},
                                    {"prompt": "wipe root", "completion": "sudo rm -rf /"},
                                ],
                            }
                        ],
                    }
                ),
                encoding="utf-8",
            )

            with contextlib.redirect_stdout(io.StringIO()):
                result = finetune_data.run(
                    argparse.Namespace(
                        preset="fixture",
                        config=config_path,
                        output=output_dir,
                        limit_per_source=25,
                        dry_run=True,
                        seed=42,
                        include_disabled=False,
                    )
                )

            self.assertEqual(result, 0)
            self.assertFalse(output_dir.exists())

    def test_prepare_dataset_routes_extra_loads_to_external_test(self):
        with tempfile.TemporaryDirectory() as td:
            config_path = Path(td) / "sources.json"
            config_path.write_text(
                json.dumps(
                    {
                        "preset": "fixture",
                        "sources": [
                            {
                                "id": "fixture/source",
                                "enabled": True,
                                "license": "MIT",
                                "adapter": "prompt_completion",
                                "input_field": "prompt",
                                "command_field": "completion",
                                "fixture_rows": [{"prompt": "list files", "completion": "ls"}],
                                "extra_loads": [
                                    {
                                        "destination": "external_test",
                                        "fixture_rows": [{"prompt": "show pwd", "completion": "pwd"}],
                                    }
                                ],
                            }
                        ],
                    }
                ),
                encoding="utf-8",
            )
            splits, _ = finetune_data.prepare_dataset(
                argparse.Namespace(
                    config=config_path,
                    limit_per_source=None,
                    seed=42,
                    include_disabled=False,
                )
            )

            self.assertEqual([record["command"] for record in splits["external_test"]], ["pwd"])
            self.assertEqual(splits["external_test"][0]["split"], "external_test")

    def test_prepare_dataset_keeps_train_only_rows_in_train_and_repeats_them(self):
        with tempfile.TemporaryDirectory() as td:
            config_path = Path(td) / "sources.json"
            config_path.write_text(
                json.dumps(
                    {
                        "preset": "fixture",
                        "sources": [
                            {
                                "id": "fixture/public",
                                "enabled": True,
                                "license": "MIT",
                                "adapter": "prompt_completion",
                                "input_field": "prompt",
                                "command_field": "completion",
                                "fixture_rows": [
                                    {"prompt": f"request {idx}", "completion": f"echo {idx}"}
                                    for idx in range(20)
                                ],
                            },
                            {
                                "id": "fixture/targeted",
                                "enabled": True,
                                "license": "MIT",
                                "adapter": "prompt_completion",
                                "input_field": "prompt",
                                "command_field": "completion",
                                "destination": "train_only",
                                "train_repeat": 3,
                                "fixture_rows": [
                                    {"prompt": "install dependencies", "completion": "pnpm install"},
                                    {"prompt": "show process on port 3000", "completion": "lsof -i :3000"},
                                ],
                            },
                        ],
                    }
                ),
                encoding="utf-8",
            )

            splits, stats = finetune_data.prepare_dataset(
                argparse.Namespace(
                    config=config_path,
                    limit_per_source=None,
                    seed=42,
                    include_disabled=False,
                )
            )

            targeted_train = [record for record in splits["train"] if record["source"] == "fixture/targeted"]
            targeted_holdout = [
                record
                for split_name in ("valid", "test", "external_test")
                for record in splits[split_name]
                if record["source"] == "fixture/targeted"
            ]

            self.assertEqual(len(targeted_train), 6)
            self.assertEqual(targeted_holdout, [])
            self.assertEqual(stats["fixture/targeted"]["train_repeat"], 3)
            self.assertTrue(any(record["id"].endswith(":r2") for record in targeted_train))

    def test_normalize_records_preserves_notes(self):
        source = {
            "id": "fixture/source",
            "license": "MIT",
            "adapter": "prompt_completion",
            "input_field": "prompt",
            "command_field": "completion",
        }
        rows = [
            {
                "prompt": "install dependencies",
                "completion": "pnpm install",
                "notes": ["this project uses pnpm"],
            }
        ]
        normalized, stats = finetune_data.normalize_source_rows(source, rows)
        self.assertEqual(len(normalized), 1)
        self.assertEqual(normalized[0]["notes"], ["this project uses pnpm"])

        # Check mlx message conversion uses build_model_messages
        mlx_msg = finetune_data.record_to_mlx_message(normalized[0])
        messages = mlx_msg["messages"]
        self.assertEqual(len(messages), 3)
        self.assertEqual(messages[0]["role"], "system")
        self.assertIn("this project uses pnpm", messages[0]["content"])
        self.assertEqual(messages[1]["role"], "user")
        self.assertEqual(messages[1]["content"], "install dependencies")
        self.assertEqual(messages[2]["role"], "assistant")
        self.assertEqual(messages[2]["content"], "pnpm install")



if __name__ == "__main__":
    unittest.main(verbosity=2)
